### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by weineran**
Editing README for testing pull_request

### CODE REVIEW

**Comment by dhimmel** [comment]
Nice now's there's something at https://github.com/dhimmel/dump-actions-context/actions?query=event:pull_request

> Would you mind approving this workflow to run so that we can get an example pull_request

I think I'll merge it to get another contributor!

**Comment by weineran** [comment]
https://github.com/dhimmel/dump-actions-context/actions/runs/3128338052/jobs/5076155307#step:2:550

So this is kinda weird...see the link above. The sha is showing as `366a3ec4d45203003f03108533f426b84ed4f3ba`. If I search the list of commits in both your repo and my fork, I don't see that commit hash anywhere. However, if I manually type it in the URL, I see it in both your repo and my fork:
* https://github.com/dhimmel/dump-actions-context/commit/366a3ec4d45203003f03108533f426b84ed4f3ba
* https://github.com/weineran/dump-actions-context/commit/366a3ec4d45203003f03108533f426b84ed4f3ba

In both cases it shows a warning in the UI: `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`
image

@dhimmel Any idea where that sha is coming from?

**Comment by dhimmel** [comment]
> Any idea where that sha is coming from?

My guess is that the `pull_request` action is creating a new merge commit to evaluate the commit in the PR after merging it into the base branch. Related discussion at https://github.com/orgs/community/discussions/25191.

**Comment by weineran** [comment]
Don't the merge commit SHAs usually show up in the list of commits here though? https://github.com/dhimmel/dump-actions-context/commits/main

🤔

**Comment by dhimmel** [comment]
> Don't the merge commit SHAs usually show up in the list of commits here though?

You won't see the merge commit created for the PR build on the main branch for 2 reasons:

- I did a squash merge, so there's not actually a merge commit on main
- Even if I did a regular merge commit to merge the PR, it would create a different commit than the one evaluated by CI, since the metadata would be different (at least the timestamps and maybe more).

Does that make sense?

**Comment by weineran** [comment]
Whoops I didn't see your respond until just now.

> Does that make sense?

Thinking about this more, I was really expecting the SHA on the PR event to match the commit of the head ref.

Re-reading further above, you mentioned that you guess the PR action is creating a new merge commit. I'm not sure why it would do that since the PR event is before anything gets merged into anything (as far as I know). That's why I'd expect the SHA on the PR event to match the commit of the head ref of the PR (i.e. https://github.com/weineran/dump-actions-context/commit/42775965ca3ce0bffd0d066224a730c411cb9b07)

I'll noodle on it a bit more and maybe play around with some PRs and see if I can wrap my head around it.

**Comment by dhimmel** [comment]
> I was really expecting the SHA on the PR event to match the commit of the head ref.

It seems odd at first but makes sense. Some notes:

- if you just want a build of the head commit, you could look at the CI for the `push` event
- a `pull_request` event is different than a `push` event in that the codebase is being evaluated for whether tests pass after you merge the PR into the base branch
- Travis and AppVeyor also do this IIRC
- if a PR has a conflict, the pull_request job doesn't run (this is a guess of what happens, can't recall off the top of my head)
- As noted in the `actions/checkout` [docs](https://github.com/actions/checkout), you can use `github.event.pull_request.head.sha` to "Checkout pull request HEAD commit instead of merge commit"

**Pull request merged**
